apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "data-stream.fullname" . }}-cron-one
  labels:
    app: {{ template "data-stream.name" . }}
    chart: {{ template "data-stream.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: {{ .Values.cronSchedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: notify-fire-points
            image: alebatt/bat
            args:
            - 'POST'
            - {{ index .Values.ingress.hosts 0 }}/v1/notify
            - 'id:admin'
            - 'x-api-key:{{ .Values.apiSecret.admin }}'
            - 'datasetId="file://fire_points_campbell_river/prot_current_fire_points.shp"'
          restartPolicy: OnFailure

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "data-stream.fullname" . }}-cron-two
  labels:
    app: {{ template "data-stream.name" . }}
    chart: {{ template "data-stream.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: {{ .Values.cronSchedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: notify-fire-poly
            image: alebatt/bat
            args:
            - 'POST'
            - {{ index .Values.ingress.hosts 0 }}/v1/notify
            - 'id:admin'
            - 'x-api-key:{{ .Values.apiSecret.admin }}'
            - 'datasetId="file://fire_polys_campbell_river/prot_current_fire_polys.shp"'
          restartPolicy: OnFailure

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "data-stream.fullname" . }}-cron-three
  labels:
    app: {{ template "data-stream.name" . }}
    chart: {{ template "data-stream.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: {{ .Values.cronSchedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: notify-lightning
            image: alebatt/bat
            args:
            - 'POST'
            - {{ index .Values.ingress.hosts 0 }}/v1/notify
            - 'id:admin'
            - 'x-api-key:{{ .Values.apiSecret.admin }}'
            - 'datasetId="file://lightning_bcalbers.csv"'
          restartPolicy: OnFailure