{{ if .Values.openshiftCICD }}

apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ template "datastream-frontend.fullname" . }}-image
  labels:
    app: {{ template "datastream-frontend.name" . }}
    chart: {{ template "datastream-frontend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  resources:
    requests:
        cpu: 2000m
        memory: 4G
    limits:
        cpu: 4000m
        memory: 8G
  output:
    to:
      kind: ImageStreamTag
      name: "{{ template "datastream-frontend.fullname" . }}-image:{{ .Values.repo.tag }}"
  source:
    type: Git
    git:
      ref: {{ .Values.repo.ref | quote }}
      uri: {{ .Values.repo.url | quote }}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: ./frontend-demo/Dockerfile
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: "GitHub"
      github: 
        secretReference:
          name: "{{ .Release.Name }}-git-webhook-secret"

{{- end }}